package main

import (
	"github.com/gin-gonic/gin"
	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

func main() {
	r := gin.Default()

	r.Run(":8000")
}
